# Travis-CI.org build script

# try the new containerized infrastructure
sudo: false

language: c
compiler:
  - gcc
  - clang

# Apparently the wcslib version they have (4.8.3) doesn't use pkg-config
# And netpbm include files are right in /usr/include, not in /usr/include/netpbm

script:
    - export WCSLIB_INC="-I/usr/include/wcslib-4.8.3"
    - export WCSLIB_LIB="-lwcs"
    - make
    - make py
    - make extra
    - make test
    - (cd util; ./test)
    - (cd blind; ./test)
    - (cd libkd; ./test)

# install:
#   - sudo apt-get update -qq
#   - sudo apt-get install -y libnetpbm10 libnetpbm10-dev wcslib-dev libcfitsio3 libcfitsio3-dev python-numpy swig gsl-bin libgsl0-dev

addons:
  apt:
    packages:
    - libnetpbm10
    - libnetpbm10-dev
    - wcslib-dev
    - libcfitsio3
    - libcfitsio3-dev
    - python-numpy
    - swig
    - gsl-bin
    - libgsl10-dev


